version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      time: '13:00'
    ignore:
      - dependency-name: "pymssql"
        versions: ["*"]
    groups:
      python-packages:
        patterns:
          - '*'
