# yaml-language-server: disable
# qualysdk documentation generation yml
site_name: qualysdk Documentation
nav:
  - Home: index.md
  - Getting Started: quickstart.md
  - Authentication: authentication.md
  - Global AssetView: gav.md
  - VMDR: vmdr.md
  - TotalCloud: totalcloud.md
  - Cloud Agent: cloud_agent.md
  - Container Security: containersecurity.md
  - Certificate View: cert.md
  - Web Application Scanning: was.md
  - Patch Management: patch.md
  - Tagging: tagging.md
  - SQL Uploads: sql.md
  - The Call Schema: callschema.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  

theme: 
  name: material
  palette:

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  features:
    - navigation.instant
    - navigation.instant.prefetch
  highlightjs: true
  user_color_mode_toggle: true
repo_url: https://github.com/0x41424142/qualysdk
repo_name: Github
edit_uri: blob/main/docs/
site_author: Jake Lindsay <jake@jakelindsay.uk>
site_description: Documentation for the qualysdk Python SDK. Make working with Qualys API data easier.
